### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by matkoniecz** [basement-labs/osmapa-garmin#2]
See https://choosealicense.com/ for tl;dr

Please, please add a license. The fact none is listed makes using this software a legal quagmire. Currently it is not legal to use this code or its derivatives in any useful software. I may be mistaken but hopefully this is not the intended effect.

Currently no license is mentioned anywhere, what makes this code fully copyrighted, like any other creative work.

It limits usefulness of this project - and I hope that it is unintentional.

In case that for some reason not releasing it under open license is intentional - mentioning it in the readme also would be a good idea.

**Comment by matkoniecz** [comment]
BTW, license for your code would need to exclude https://github.com/basement-labs/osmapa-garmin/tree/master/bin (and it is likely that these files need a separate licenses - or maybe it should be replaced by some sort of dependency management)?

**Comment by basement-labs** [comment]
Hi!

Some time ago I've added a license to the project. It's compatible with
mkgmap license whole work is based on.

MR

**Comment by matkoniecz** [comment]
https://github.com/basement-labs/osmapa-garmin/blob/master/LICENSE

Thanks!
